config/routes.rb
MusicLibrary::Application.routes.draw do
  resources :albums

  root 'welcome#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :title, presence: true,
                    length: { minimum: 1 }

   validates :artist, presence: true,
                    length: { minimum: 1 }

   validates :genre, presence: true,
                    length: { minimum: 1 }
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	def new
		@album = Album.new
	end

	def create
		#render text: params[:album].inspect
		@album = Album.new(album_params)
 
 		if @album.save
  			redirect_to @album
  		else
  			render 'new'
  		end
  	end

  	def show
  		@album = Album.find(params[:id])
	end

	def index
  		@albums = Album.all
	end
	
  def edit
      @album = Album.find(params[:id])
  end

  def update
      @album = Album.find(params[:id])
 
      if @album.update(album_params)
        redirect_to @album
      else
        render 'edit'
      end
  end

  def destroy
      @album = Album.find(params[:id])
      @album.destroy
 
      redirect_to albums_path
  end

  	private
  		def album_params
    		params.require(:album).permit(:title, :artist, :genre, :released)
  		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= form_for @album do |f| %>
  <% if @album.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@album.errors.count, "error") %> prohibited
      this album from being saved:</h2>
    <ul>
    <% @album.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>
 <p>
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </p>
  <p>
    <%= f.label :released %><br>
    <%= f.date_select :released, :start_year=>1900, :end_year => 2020 %>
  </p>

  <p>
    <%= f.submit :onclick => "return confirm('Are you sure?')" %>
  </p>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Artist</th>
    <th>Genre</th>
    <th>Released Date</th>
    <th colspan="3"></th>
  </tr>
 
  <% @albums.each do |album| %>
    <tr>
      <td><%= album.title %></td>
      <td><%= album.artist %></td>
      <td><%= album.genre %></td>
      <td><%= album.released %></td>
      <td><%= link_to 'Show', album_path(album) %></td>
      <td><%= link_to 'Edit', edit_album_path(album) %></td>
      <td><%= link_to 'Destroy', album_path(album),
                    method: :delete, data: { confirm: 'Deleting an album. Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br>
<br>
<%= link_to 'Back to Main Page', root_path %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/albums/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>
 
<p>
  <strong>Artist:</strong>
  <%= @album.artist %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @album.genre %>
</p>

<p>
  <strong>Released:</strong>
  <%= @album.released %>
</p>

<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicLibrary</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to my Album</h1>

<%= link_to 'Link to My Albums', controller: 'albums' %>

<br>
<br>

<%= link_to 'Create New a Album', new_album_path %>